modLoader="javafml"
loaderVersion="[35,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/pigpen/issues"
license="LGPL v2.1"

[[mods]]
modId="pigpen"
updateJSONURL="https://updates.blamejared.com/get?n=pigpen&gv=1.16.4"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.pigpen]]
    modId="forge"
    mandatory=true
    versionRange="[35,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.pigpen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"